### ISSUE TITLE
Does this work for vue js 2?

### ISSUE THREAD

**Issue by mirikerstein** [nonide/vuejs-count-down#1]
Thanks a lot! 
Also, anywhere to see a live demo?

**Comment by nonide** [comment]
Yes, it works in VueJS 2 :)

And sorry, I don't have any site to see it for the moment 😞

**Comment by mirikerstein** [comment]
Thanks a lot for your response! How about I'll try to set up a simple
fiddle and reach out to you if I have any questions. I really appreciate
it.

**Comment by nonide** [comment]
No problem!
